{{- if .Values.postgres.enabled }}
---
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-postgres-init"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Files.Get "files/retail_database/init.sql" | indent 4 }}
{{- end }}
